#!/usr/bin/env bash

/usr/local/sbin/update_cron
/usr/local/emhttp/plugins/user.scripts/startSchedule.php start

if [ ! -e /tmp/user.scripts/booted ]
  then
    mkdir -p "/tmp/user.scripts/"
    echo "booted" > /tmp/user.scripts/booted
    /usr/local/emhttp/plugins/user.scripts/startSchedule.php boot
fi
